export default {
    title: '2020 OOCL ITA AFS Bootcamp Report',
    date_range: '12/10 - 06/11',
    overall_ranking: 'Overall Ranking',
    comprehensive_ranking: 'Comprehensive ranking of all students',
    overall_ranking_des: 'The weight of technical ability and learning ability is 3, and the weight of understanding ability and communication ability is 2.',
    ability_ranking: 'Students\' Ability Ranking',
    dimensional_ranking: 'Ranking of different dimensional capabilities of all students',
    technical_ranking: 'Technical Ability Ranking',
    learning_ranking: 'Learning Ability Ranking',
    comprehension_ranking: 'Comprehension Ability Ranking',
    communication_ranking: 'Communication Ability Ranking',
    detail_report: '\'s detail report',
    detail_report_des: 'Including the ability statistics graph of the student\'s overall ability in each dimension, the chronological trend chart of the quality of each assignment, the distribution of the student\'s all assignment quality scores, and the detailed score of each item in each dimension.',
    homework_ranking: 'Homework Quality Ranking',
    all_homework_ranking: 'Homework quality ranking of all students',
    platform_score_ranking: 'Learning Platform Scores Ranking',
    platform_score_ranking_des: 'This result only counts homework completion scores and acceptance questions scores.',
    ability_overview: 'Overview of students\' abilities',
    dimension_results: 'Statistical results of all students in different dimensions',
    technical_skills: 'Technical skills',
    learning_ability: 'Learning ability',
    comprehension: 'Comprehension',
    communication: 'Communication skills',
    level_overview: 'Overview of students ranking',
    level_overview_des: 'Statistics based on the overall performance of the students',
    ability_chart: '\'s ability chart',
    homework_chart: '\'s homework quality overview',
    quality_chart: '\'s quality chart of each assignment',
    detail_dimension_score: '\'s detailed scores for each dimension ability',
}
