export default {
    title: '2020 OOCL ITA AFS Bootcamp Report',
    date_range: '12/10 - 06/11',
    overall_ranking: 'Overall Ranking',
    comprehensive_ranking: 'Comprehensive ranking of all students',
    overall_ranking_des: 'The weight of technical ability and learning ability is 3, and the weight of understanding ability and communication ability is 2.',
    ability_ranking: 'Students\' Ability Ranking',
    dimensional_ranking: 'Ranking of different dimensional capabilities of all students',
    technical_ranking: 'Technical Ability Ranking',
    learning_ranking: 'Learning Ability Ranking',
    comprehension_ranking: 'Comprehension Ability Ranking',
    communication_ranking: 'Communication Ability Ranking',
    detail_report: '\'s Detail Report',
    detail_report_des: 'Including the ability statistics graph of the student\'s overall ability in each dimension, the chronological trend chart of the quality of each assignment, the distribution of the student\'s all assignment quality scores, and the detailed score of each item in each dimension.',
    homework_ranking: 'Homework Quality Ranking',
    all_homework_ranking: 'Homework quality ranking of all students',
    platform_score_ranking: 'Learning Platform Scores Ranking',
    platform_score_ranking_des: 'This result only counts homework completion scores and acceptance questions scores.',
    ability_overview: 'Overview of students\' abilities',
    dimension_results: 'Statistical results of all students in different dimensions',
    technical_skills: 'Technical skills',
    learning_ability: 'Learning ability',
    comprehension: 'Comprehension',
    communication: 'Communication skills',
    level_overview: 'Overview of students ranking',
    level_overview_des: 'Statistics based on the overall performance of the students',
    ability_chart: '\'s ability chart',
    homework_chart: '\'s homework quality overview',
    quality_chart: '\'s quality chart of each assignment',
    detail_dimension_score: '\'s detailed scores for each dimension ability',
    tech_behavior_1: '每次任务都有验收思想',
    tech_behavior_2: '有代码设计',
    tech_behavior_3: '每次练习都能做到职责单一',
    tech_behavior_4: '代码编写满足clean code',
    tech_behavior_5: '能较快的完成各类练习',
    tech_behavior_6: '能通过搜集信息快速定位问题',
    tech_behavior_7: '能利用资源完成任务',
    tech_behavior_8: '能解决问题',
    learn_behavior_1: '有小步迭代思想',
    learn_behavior_2: '遵循最佳实践',
    learn_behavior_3: '能从他人身上学习',
    learn_behavior_4: '坚持每日写总结',
    learn_behavior_5: '有很好的执行力',
    learn_behavior_6: '能分清优先级',
    learn_behavior_7: '有良好的工作习惯',
    learn_behavior_8: '每天都有持续改进',
    comprehension_behavior_1: '能做任务分解',
    comprehension_behavior_2: '能接受他人的反馈并改进',
    comprehension_behavior_3: '拿到任务能做到需求澄清',
    comprehension_behavior_4: '能理解练习的需求',
    comprehension_behavior_5: '能发现他人代码中的问题',
    comprehension_behavior_6: '能理解新知识',
    comprehension_behavior_7: '能使用有业务意义的git commit',
    comprehension_behavior_8: '能使用有业务意义的代码命名',
    communication_behavior_1: '能积极提供支持或帮助',
    communication_behavior_2: '能积极参与小组内讨论',
    communication_behavior_3: '有良好的团队协作能力',
    communication_behavior_4: '能产生有效对话',
    communication_behavior_5: '能积极回答问题',
    communication_behavior_6: '能积极寻求帮助',
    communication_behavior_7: '能积极给出反馈',
    communication_behavior_8: '能积极分享观点或技能',
}
