export default {
    title: '2020 OOCL ITA AFS Bootcamp Report',
    date_range: '12/10 - 06/11',
    overall_ranking: 'Overall Ranking',
    comprehensive_ranking: 'Comprehensive ranking of all students',
    overall_ranking_des: 'The weight of technical ability and learning ability is 3, and the weight of understanding ability and communication ability is 2.',
    ability_ranking: 'Students\' Ability Ranking',
    dimensional_ranking: 'Ranking of different dimensional capabilities of all students',
    technical_ranking: 'Technical Ability Ranking',
    learning_ranking: 'Learning Ability Ranking',
    comprehension_ranking: 'Comprehension Ability Ranking',
    communication_ranking: 'Communication Ability Ranking',
    detail_report: '\'s Detail Report',
    detail_report_des: 'Including the ability statistics graph of the student\'s overall ability in each dimension, the chronological trend chart of the quality of each assignment, the distribution of the student\'s all assignment quality scores, and the detailed score of each item in each dimension.',
    homework_ranking: 'Homework Quality Ranking',
    all_homework_ranking: 'Homework quality ranking of all students',
    platform_score_ranking: 'Learning Platform Scores Ranking',
    platform_score_ranking_des: 'This result only counts homework completion scores and acceptance questions scores.',
    ability_overview: 'Overview of students\' abilities',
    dimension_results: 'Statistical results of all students in different dimensions',
    technical_skills: 'Technical skills',
    learning_ability: 'Learning ability',
    comprehension: 'Comprehension',
    communication: 'Communication skills',
    level_overview: 'Overview of students ranking',
    level_overview_des: 'Statistics based on the overall performance of the students',
    ability_chart: '\'s ability chart',
    homework_chart: '\'s homework quality overview',
    quality_chart: '\'s quality chart of each assignment',
    detail_dimension_score: '\'s detailed scores for each dimension ability',
    tech_behavior_1: 'Every task has acceptance thought',
    tech_behavior_2: 'Code design',
    tech_behavior_3: 'Each practice can be single responsibility',
    tech_behavior_4: 'Clean code',
    tech_behavior_5: 'Can complete assignments quickly',
    tech_behavior_6: 'Can quickly locate problems',
    tech_behavior_7: 'Can use resources to complete tasks',
    tech_behavior_8: 'Can solve the problem',
    learn_behavior_1: 'Has small step iteration thought',
    learn_behavior_2: 'Follow best practices',
    learn_behavior_3: 'Can learn from others',
    learn_behavior_4: 'Stick to daily diary',
    learn_behavior_5: 'Has good execution',
    learn_behavior_6: 'Prioritize',
    learn_behavior_7: 'Has good working habits',
    learn_behavior_8: 'Continuous improvement every day',
    comprehension_behavior_1: 'Can do tasking',
    comprehension_behavior_2: 'Can accept feedback from others and improve',
    comprehension_behavior_3: 'Can clarify the needs when get the task',
    comprehension_behavior_4: 'Understand the needs of the practice',
    comprehension_behavior_5: 'Can find problems in other people\'s code',
    comprehension_behavior_6: 'Can understand new knowledge',
    comprehension_behavior_7: 'Able to use business-meaning git commit',
    comprehension_behavior_8: 'Able to name with business-meaning code',
    communication_behavior_1: 'Can actively provide support or help',
    communication_behavior_2: 'Can actively participate in group discussions',
    communication_behavior_3: 'Has good teamwork skills',
    communication_behavior_4: 'Can produce effective dialogue',
    communication_behavior_5: 'Can actively answer questions',
    communication_behavior_6: 'Can actively seek help',
    communication_behavior_7: 'Can actively give feedback',
    communication_behavior_8: 'Can actively share ideas or skills',
}
