export default {
    title: '2020 OOCL ITA AFS Bootcamp 报告',
    date_range: '10月12日 - 11月06日',
    overall_ranking: '总排名',
    comprehensive_ranking: '所有学员总体能力得分的综合排名',
    overall_ranking_des: '技术能力和学习能力权重是3，理解能力和沟通能力权重是2',
    ability_ranking: '学员能力排名',
    dimensional_ranking: '所有学员不同维度能力的排名结果',
    technical_ranking: '技术能力排名',
    learning_ranking: '学习能力排名',
    comprehension_ranking: '理解能力排名',
    communication_ranking: '沟通能力排名',
    detail_report: '的详细报告',
    homework_ranking: '作业质量排名',
    all_homework_ranking: '所有学员的作业质量得分排名结果',
}
