export default {
    title: '2021 AeXL AFS Bootcamp 报告',
    date_range: '10月18日 - 11月12日',
    overall_ranking: '总排名',
    comprehensive_ranking: '所有学员总体能力得分的综合排名',
    overall_ranking_des: '技术能力和学习能力权重是3，理解能力和沟通能力权重是2',
    ability_ranking: '学员能力排名',
    dimensional_ranking: '所有学员不同维度能力的排名结果',
    technical_ranking: '技术能力排名',
    learning_ranking: '学习能力排名',
    comprehension_ranking: '理解能力排名',
    communication_ranking: '沟通能力排名',
    detail_report: '的详细报告',
    detail_report_des: '包括该学员各维度总体能力的能力图统计，每次作业质量按时间顺序的走势图，学员所有作业质量得分的分布，以及各维度的每一项的详细得分。',
    homework_ranking: '作业质量排名',
    all_homework_ranking: '所有学员的作业质量得分排名结果',
    platform_score_ranking: '学习平台积分排名',
    platform_score_ranking_des: '此结果统计了平台上所有练习的得分。',
    ability_overview: '学员能力总览',
    dimension_results: '所有学员分不同维度的统计结果',
    technical_skills: '技术能力',
    learning_ability: '学习能力',
    comprehension: '理解能力',
    communication: '沟通能力',
    level_overview: '学员等级总览',
    level_overview_des: '根据学员整体表现情况统计的结果',
    ability_chart: '的能力图',
    homework_chart: '的作业质量总览',
    quality_chart: '的每次作业质量走势图',
    detail_dimension_score: '各维度能力详细得分',
    position_description: '当前综合分数',
    current_score: '当前分数',

    tech_behavior_1: '验收思想',
    tech_behavior_2: '代码质量高',
    tech_behavior_3: '快速完成任务',
    tech_behavior_4: '定位问题',
    tech_behavior_5: '解决问题',

    learn_behavior_1: '遵循最佳实践',
    learn_behavior_2: '从他人身上学习',
    learn_behavior_3: '工作习惯',
    learn_behavior_4: '执行力',
    learn_behavior_5: '持续改进',

    comprehension_behavior_1: '接受反馈',
    comprehension_behavior_2: '需求澄清',
    comprehension_behavior_3: '理解需求',
    comprehension_behavior_4: '发现他人的问题',
    comprehension_behavior_5: '理解新知识',

    communication_behavior_1: '积极讨论',
    communication_behavior_2: '回答问题',
    communication_behavior_3: '寻求帮助',
    communication_behavior_4: '提供帮助',
    communication_behavior_5: '分享'
}
