export default {
    title: '2020 OOCL ITA AFS Bootcamp 报告',
    date_range: '10月12日 - 11月06日',
    overall_ranking: '总排名',
    comprehensive_ranking: '所有学员总体能力得分的综合排名',
    overall_ranking_des: '技术能力和学习能力权重是3，理解能力和沟通能力权重是2',
    ability_ranking: '学员能力排名',
    dimensional_ranking: '所有学员不同维度能力的排名结果',
    technical_ranking: '技术能力排名',
    learning_ranking: '学习能力排名',
    comprehension_ranking: '理解能力排名',
    communication_ranking: '沟通能力排名',
    detail_report: '的详细报告',
    detail_report_des: '包括该学员各维度总体能力的能力图统计，每次作业质量按时间顺序的走势图，学员所有作业质量得分的分布，以及各维度的每一项的详细得分。',
    homework_ranking: '作业质量排名',
    all_homework_ranking: '所有学员的作业质量得分排名结果',
    platform_score_ranking: '学习平台积分排名',
    platform_score_ranking_des: '此结果仅统计作业完成度得分和验收题得分。',
    ability_overview: '学员能力总览',
    dimension_results: '所有学员分不同维度的统计结果',
    technical_skills: '技术能力',
    learning_ability: '学习能力',
    comprehension: '理解能力',
    communication: '沟通能力',
    level_overview: '学员等级总览',
    level_overview_des: '根据学员整体表现情况统计的结果',
    ability_chart: '的能力图',
}
